# -*- coding: utf-8 -*-
"""rep_revenue_per_customer_and_period.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cr57yiStkc5TkIrGltdowgos1mCIJ-t5
"""

from google.cloud import bigquery
import pandas as pd
from pandas_gbq import to_gbq
import os

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/content/drive/MyDrive/gcp/arcane-dynamics-444918-f3-bc146cb97ba7.json"

project_id = 'arcane-dynamics-444918-f3'
dataset_id = 'reporting_db'
table_id = 'rep_revenue_per_customer_and_period'

client = bigquery.Client(project = project_id)


query = """
WITH reporting_dates AS (
  SELECT
    reporting_date,
    reporting_period
  FROM `arcane-dynamics-444918-f3.reporting_db.reporting_periods_table`
  WHERE reporting_period IN ('Day', 'Month', 'Year')
    AND EXTRACT(YEAR FROM reporting_date) IN (2022, 2023, 2024)
)
, customers as (
  select *
  from arcane-dynamics-444918-f3.staging_db.stg_customer
)
, payments AS (
  SELECT
    CAST(pay.payment_date AS DATE) AS payment_date,
    ren.rental_customer,
    film.film_title,
    pay.payment_amount
  FROM `arcane-dynamics-444918-f3.staging_db.stg_payment` AS pay
  LEFT JOIN `arcane-dynamics-444918-f3.staging_db.stg_rental` AS ren
    ON pay.payment_rental_id = ren.rental_id
  LEFT JOIN `arcane-dynamics-444918-f3.staging_db.stg_inventory` AS inv
    ON ren.rental_inventory = inv.inventory_id
  LEFT JOIN `arcane-dynamics-444918-f3.staging_db.stg_film` AS film
    ON inv.inventory_film_id = film.film_id
  WHERE film.film_title <> 'GOODFELLAS SALUTE'
)
, revenue_per_period_day as (
  select
    'Day' as reporting_period
    , date_trunc(payments.payment_date, day) as reporting_date
    , customers.customer_id
    , sum(payments.payment_amount) as revenue
    from payments
    left join customers on payments.rental_customer=customers.customer_id
    group by 1,2,3
)

, revenue_per_period_month as (
  select
    'Month' as reporting_period
    , date_trunc(payments.payment_date, month) as reporting_date
    , customers.customer_id
    , sum(payments.payment_amount) as revenue
    from payments
    left join customers on payments.rental_customer=customers.customer_id
    group by 1,2,3
)
, revenue_per_period_year as (
  select
    'Year' as reporting_period
    , date_trunc(payments.payment_date, year) as reporting_date
    , customers.customer_id
    , sum(payments.payment_amount) as revenue
    from payments
    left join customers on payments.rental_customer=customers.customer_id
    group by 1,2,3
)
, revenue_per_period as (
  select *
  from revenue_per_period_day
  union all
  select *
  from revenue_per_period_month
  union all
  select *
  from revenue_per_period_year
)
, final_day as (
  select
  reporting_dates.reporting_period
  , reporting_dates.reporting_date
  , revenue_per_period.customer_id
  , coalesce(revenue_per_period.revenue, 0) as total_revenue
  from reporting_dates
  left join revenue_per_period
  on reporting_dates.reporting_period = revenue_per_period.reporting_period
  and reporting_dates.reporting_date = revenue_per_period.reporting_date
  where reporting_dates.reporting_period = 'Day'
)
, final_month as (
  select
  reporting_dates.reporting_period
  , reporting_dates.reporting_date
  , revenue_per_period.customer_id
  , coalesce(revenue_per_period.revenue, 0) as total_revenue
  from reporting_dates
  left join revenue_per_period
  on reporting_dates.reporting_period = revenue_per_period.reporting_period
  and reporting_dates.reporting_date = revenue_per_period.reporting_date
  where reporting_dates.reporting_period = 'Month'
)
, final_year as (
  select
  reporting_dates.reporting_period
  , reporting_dates.reporting_date
  , revenue_per_period.customer_id
  , coalesce(revenue_per_period.revenue, 0) as total_revenue
  from reporting_dates
  left join revenue_per_period
  on reporting_dates.reporting_period = revenue_per_period.reporting_period
  and reporting_dates.reporting_date = revenue_per_period.reporting_date
  where reporting_dates.reporting_period = 'Year'
)
,final as (
  select * from final_day
  union all
  select * from final_month
  union all
  select * from final_year
)
select customer_id, reporting_period, reporting_date, total_revenue from final;


"""

df = client.query(query).to_dataframe()

df.head()

', '.join(df.columns)

"""# Write to BigQuery

"""

full_table_id = f"{project_id}.{dataset_id}.{table_id}"


schema = [
  bigquery.SchemaField("customer_id", "INTEGER"),
  bigquery.SchemaField("reporting_period", "STRING"),
  bigquery.SchemaField("reporting_date", "DATETIME"),
  bigquery.SchemaField("total_revenue", "FLOAT")
]

client = bigquery.Client(project = project_id)

def table_exists(client, table_ref):
    from google.cloud.exceptions import NotFound
    try:
        client.get_table(table_ref)
        return True
    except NotFound:
        return False

if table_exists(client, full_table_id):
    destination_table = f"{dataset_id}.{table_id}"
    to_gbq(df, destination_table, project_id=project_id, if_exists="replace", table_schema=schema)
    print(f"{destination_table} table exists in BigQuery. Overwritten.")
else:

    job_config = bigquery.LoadJobConfig(schema = schema)
    job = client.load_table_from_dataframe(df, full_table_id, job_config=job_config)
    job.result()
    print(f"Table {full_table_id} table created in BigQuery and data loaded")