# -*- coding: utf-8 -*-
"""stg_film.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cr57yiStkc5TkIrGltdowgos1mCIJ-t5
"""

from google.cloud import bigquery
import pandas as pd
from pandas_gbq import to_gbq
import os

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/content/drive/MyDrive/gcp/arcane-dynamics-444918-f3-bc146cb97ba7.json"

project_id = 'arcane-dynamics-444918-f3'
dataset_id = 'staging_db'
table_id = 'stg_film'

client = bigquery.Client(project = project_id)


query = """
with base as (
  select * from `arcane-dynamics-444918-f3.public.film`
)

, final as (
  select film_id
    , title as film_title
    , description as film_description
    , language_id as film_language_id
    , original_language_id as film_original_language_id
    , rental_duration as film_rental_duration
    , rental_rate as film_rental_rate
    , length as film_length
    , replacement_cost as film_replacement_cost
    , rating as film_rating
    , last_update as film_last_update
    , special_features as film_special_features
    , fulltext as film_fulltext
  from base

)

select * from final;

"""

df = client.query(query).to_dataframe()

df.head()

', '.join(df.columns)

"""# Write to BigQuery

"""

full_table_id = f"{project_id}.{dataset_id}.{table_id}"


schema = [
  bigquery.SchemaField("film_id", "INTEGER"),
  bigquery.SchemaField("film_title", "STRING"),
  bigquery.SchemaField("film_description", "STRING"),
  bigquery.SchemaField("film_language_id", "INTEGER"),
  bigquery.SchemaField("film_original_language_id", "INTEGER"),
  bigquery.SchemaField("film_rental_duration", "INTEGER"),
  bigquery.SchemaField("film_rental_rate", "INTEGER"),
  bigquery.SchemaField("film_length", "INTEGER"),
  bigquery.SchemaField("film_replacement_cost", "INTEGER"),
  bigquery.SchemaField("film_rating", "STRING"),
  bigquery.SchemaField("film_last_update", "DATETIME"),
  bigquery.SchemaField("film_special_features", "STRING"),
  bigquery.SchemaField("film_fulltext", "STRING")
]

client = bigquery.Client(project = project_id)

def table_exists(client, table_ref):
    from google.cloud.exceptions import NotFound
    try:
        client.get_table(table_ref)
        return True
    except NotFound:
        return False

if table_exists(client, full_table_id):
    destination_table = f"{dataset_id}.{table_id}"
    to_gbq(df, destination_table, project_id=project_id, if_exists="replace", table_schema=schema)
    print(f"{destination_table} table exists in BigQuery. Overwritten.")
else:

    job_config = bigquery.LoadJobConfig(schema = schema)
    job = client.load_table_from_dataframe(df, full_table_id, job_config=job_config)
    job.result()
    print(f"Table {full_table_id} table created in BigQuery and data loaded")