# -*- coding: utf-8 -*-
"""stg_film_category.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cr57yiStkc5TkIrGltdowgos1mCIJ-t5
"""

from google.cloud import bigquery
import pandas as pd
from pandas_gbq import to_gbq
import os

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/content/drive/MyDrive/gcp/arcane-dynamics-444918-f3-bc146cb97ba7.json"

project_id = 'arcane-dynamics-444918-f3'
dataset_id = 'staging_db'
table_id = 'stg_film_category'

client = bigquery.Client(project = project_id)


query = """
with base as (
  select * from `arcane-dynamics-444918-f3.public.film_category`
)

, final as (
  select
  film_id as film_category_film_id
  , category_id as film_category_category_id
  , last_update as film_category_last_update
from base

)

select * from final;

"""

df = client.query(query).to_dataframe()

df.head()

df.columns

"""# Write to BigQuery

"""

full_table_id = f"{project_id}.{dataset_id}.{table_id}"


schema = [
  bigquery.SchemaField("film_category_film_id", "INTEGER"),
  bigquery.SchemaField("film_category_category_id", "INTEGER"),
  bigquery.SchemaField("film_category_last_update", "DATETIME")
]

client = bigquery.Client(project = project_id)

def table_exists(client, table_ref):
    from google.cloud.exceptions import NotFound
    try:
        client.get_table(table_ref)
        return True
    except NotFound:
        return False

if table_exists(client, full_table_id):
    destination_table = f"{dataset_id}.{table_id}"
    to_gbq(df, destination_table, project_id=project_id, if_exists="replace", table_schema=schema)
    print(f"{destination_table} table exists in BigQuery. Overwritten.")
else:

    job_config = bigquery.LoadJobConfig(schema = schema)
    job = client.load_table_from_dataframe(df, full_table_id, job_config=job_config)
    job.result()
    print(f"Table {full_table_id} table created in BigQuery and data loaded")